version: '3'

services:
  nodered:
    build: ./nodered
    container_name: 'nodered'
    ports:
      - '1880:1880'
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: 'mqttserver'
    ports:
      - '1883:1883'
      - '9001:9001'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27017:27017'